server:
  port: ${ANSWERING_APP_PORT:9090}

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_LOCAL_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect:  org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    validate-on-migrate: true
rabbitmq:
  username:           ${MQ_USERNAME}
  password:           ${MQ_PASSWORD}
  host:               ${MQ_HOST}
  port:               ${MQ_LOCAL_PORT}
  virtualHost:        ${MQ_VIRTUAL_HOST}
  exchange:           ${MQ_EXCHANGE}
  messageRoutingKey:  ${MQ_MESSAGE_ROUTING_KEY}
  mailRoutingKey:     ${MQ_MAIL_ROUTING_KEY}
  statusRoutingKey:   ${MQ_STATUS_ROUTING_KEY}
  messageQueue:       ${MQ_MESSAGE_QUEUE}
  mailQueue:          ${MQ_MAIL_QUEUE}
  statusQueue:        ${MQ_STATUS_QUEUE}